
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMES\n    geral : expression\n    \n    expression : term expres\n    \n    expres : PLUS expression\n    \n    expres : MINUS expression\n    \n    expres : empty\n    \n    term : factor termaux\n    \n    termaux : TIMES term\n    \n    termaux : DIVIDE term\n    \n    termaux : empty\n    \n    factor : LPAREN expression RPAREN\n    \n    factor : NUMBER\n    \n    empty :\n    '
    
_lr_action_items = {'LPAREN':([0,5,8,9,12,13,],[5,5,5,5,5,5,]),'NUMBER':([0,5,8,9,12,13,],[6,6,6,6,6,6,]),'$end':([1,2,3,4,6,7,10,11,14,16,17,18,19,20,],[0,-1,-12,-12,-11,-2,-5,-6,-9,-3,-4,-7,-8,-10,]),'PLUS':([3,4,6,11,14,18,19,20,],[8,-12,-11,-6,-9,-7,-8,-10,]),'MINUS':([3,4,6,11,14,18,19,20,],[9,-12,-11,-6,-9,-7,-8,-10,]),'RPAREN':([3,4,6,7,10,11,14,15,16,17,18,19,20,],[-12,-12,-11,-2,-5,-6,-9,20,-3,-4,-7,-8,-10,]),'TIMES':([4,6,20,],[12,-11,-10,]),'DIVIDE':([4,6,20,],[13,-11,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'geral':([0,],[1,]),'expression':([0,5,8,9,],[2,15,16,17,]),'term':([0,5,8,9,12,13,],[3,3,3,3,18,19,]),'factor':([0,5,8,9,12,13,],[4,4,4,4,4,4,]),'expres':([3,],[7,]),'empty':([3,4,],[10,14,]),'termaux':([4,],[11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> geral","S'",1,None,None,None),
  ('geral -> expression','geral',1,'p_geral','Yaccer.py',7),
  ('expression -> term expres','expression',2,'p_expression','Yaccer.py',14),
  ('expres -> PLUS expression','expres',2,'p_expres_plus','Yaccer.py',20),
  ('expres -> MINUS expression','expres',2,'p_expres_minus','Yaccer.py',26),
  ('expres -> empty','expres',1,'p_expres_empty','Yaccer.py',32),
  ('term -> factor termaux','term',2,'p_term','Yaccer.py',38),
  ('termaux -> TIMES term','termaux',2,'p_termaux_times','Yaccer.py',44),
  ('termaux -> DIVIDE term','termaux',2,'p_termaux_divide','Yaccer.py',50),
  ('termaux -> empty','termaux',1,'p_termaux_empty','Yaccer.py',56),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_parentheses','Yaccer.py',62),
  ('factor -> NUMBER','factor',1,'p_factor_number','Yaccer.py',68),
  ('empty -> <empty>','empty',0,'p_empty','Yaccer.py',74),
]
